# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Corsair.iCUE.5
PackageVersion: 5.2.128
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
UpgradeBehavior: install
Installers:
- InstallerUrl: https://downloads.corsair.com/Files/icue/Install-iCUE.exe
  Architecture: x64
  InstallerType: exe
  InstallerSha256: 3D7E26AE1362AD00330801CACFA8A44D7C511CCC6552878B6BD84FBB163FB85A
ManifestType: installer
ManifestVersion: 1.4.0
